version: '3.4'

services:
  securecodingsandbox:
    build:
      context: .
      dockerfile: SecureCodingSandbox/Dockerfile

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: app 
      POSTGRES_USER: admin 
      POSTGRES_PASSWORD: password 
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: always

volumes:
  dbdata:
