version: '3.8'

services:
  securecodingsandbox:
    build:
      context: .
      dockerfile: SecureCodingSandbox/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=app;Username=admin;Password=password

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: app 
      POSTGRES_USER: admin 
      POSTGRES_PASSWORD: password 
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: always

volumes:
  dbdata:
